FROM python:3.11

RUN pip install --upgrade pip
RUN pip install anndata \
                mudata \
                spatialdata \
                scanpy \
                muon \
                scvi-tools \
                scirpy \
                squidpy \
                spatialdata_io \
                seaborn \
                pandas
