FROM python:3.11

RUN pip install --upgrade pip

RUN pip install anndata \
                spatialdata \
                scanpy \
                spatialdata_io \
                seaborn \
                pandas \
                boto3 \
                pydeseq2
                
